# Form implementation generated from reading ui file 'd:\MyNewWork\yandex\books\book_searcher.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 445)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 541, 361))
        self.tableView.setObjectName("tableView")
        self.db_connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.db_connect.setGeometry(QtCore.QRect(580, 170, 171, 51))
        self.db_connect.setObjectName("db_connect")
        self.search_method = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_method.setGeometry(QtCore.QRect(580, 90, 171, 51))
        self.search_method.setObjectName("search_method")
        self.update_info = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update_info.setGeometry(QtCore.QRect(580, 250, 171, 51))
        self.update_info.setObjectName("update_info")
        self.search_method_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_method_2.setGeometry(QtCore.QRect(580, 330, 171, 51))
        self.search_method_2.setObjectName("search_method_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.db_connect.setText(_translate("MainWindow", "Подключить БД"))
        self.search_method.setText(_translate("MainWindow", "Поиск"))
        self.update_info.setText(_translate("MainWindow", "Обновить информацию или заметки"))
        self.search_method_2.setText(_translate("MainWindow", "Добавить книгу"))
