# Form implementation generated from reading ui file 'd:\MyNewWork\yandex\book_search\book_search\data\adding_with_new.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.sureButton = QtWidgets.QPushButton(parent=Dialog)
        self.sureButton.setGeometry(QtCore.QRect(80, 270, 201, 23))
        self.sureButton.setObjectName("sureButton")
        self.author_name = QtWidgets.QTextEdit(parent=Dialog)
        self.author_name.setGeometry(QtCore.QRect(20, 20, 181, 21))
        self.author_name.setAcceptRichText(True)
        self.author_name.setObjectName("author_name")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(220, 20, 131, 16))
        self.label.setObjectName("label")
        self.book_name = QtWidgets.QTextEdit(parent=Dialog)
        self.book_name.setGeometry(QtCore.QRect(20, 50, 181, 21))
        self.book_name.setObjectName("book_name")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 131, 16))
        self.label_2.setObjectName("label_2")
        self.information = QtWidgets.QTextEdit(parent=Dialog)
        self.information.setGeometry(QtCore.QRect(20, 100, 181, 141))
        self.information.setObjectName("information")
        self.notes = QtWidgets.QTextEdit(parent=Dialog)
        self.notes.setGeometry(QtCore.QRect(210, 100, 181, 141))
        self.notes.setObjectName("notes")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(220, 80, 131, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sureButton.setText(_translate("Dialog", "Добавить книгу"))
        self.label.setText(_translate("Dialog", "Имя автора"))
        self.label_2.setText(_translate("Dialog", "Название книги"))
        self.label_3.setText(_translate("Dialog", "Информация"))
        self.label_4.setText(_translate("Dialog", "Заметки"))
