# Form implementation generated from reading ui file 'd:\MyNewWork\yandex\book_search\book_search\data\adding.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.book_name = QtWidgets.QTextEdit(parent=Dialog)
        self.book_name.setGeometry(QtCore.QRect(20, 20, 171, 21))
        self.book_name.setObjectName("book_name")
        self.info = QtWidgets.QTextEdit(parent=Dialog)
        self.info.setGeometry(QtCore.QRect(20, 80, 171, 181))
        self.info.setObjectName("info")
        self.notes = QtWidgets.QTextEdit(parent=Dialog)
        self.notes.setGeometry(QtCore.QRect(210, 80, 171, 181))
        self.notes.setObjectName("notes")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(210, 20, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 60, 121, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 270, 151, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Введите название книги"))
        self.label_2.setText(_translate("Dialog", "Информация"))
        self.label_3.setText(_translate("Dialog", "Заметки"))
        self.pushButton.setText(_translate("Dialog", "Добавить книгу"))
