# Form implementation generated from reading ui file 'd:\MyNewWork\yandex\book_search\book_search\data\asking.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.sure_button = QtWidgets.QPushButton(parent=Form)
        self.sure_button.setGeometry(QtCore.QRect(80, 250, 221, 23))
        self.sure_button.setObjectName("sure_button")
        self.inform = QtWidgets.QTextEdit(parent=Form)
        self.inform.setGeometry(QtCore.QRect(10, 50, 181, 181))
        self.inform.setObjectName("inform")
        self.notes = QtWidgets.QTextEdit(parent=Form)
        self.notes.setGeometry(QtCore.QRect(210, 50, 181, 181))
        self.notes.setObjectName("notes")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 71, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sure_button.setText(_translate("Form", "Подтвердить изменения"))
        self.label.setText(_translate("Form", "Информация"))
        self.label_2.setText(_translate("Form", "Заметки"))
