# Form implementation generated from reading ui file 'd:\MyNewWork\yandex\book_search\book_search\data\book_searcher.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Book Searcher")
        MainWindow.resize(783, 445)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 541, 361))
        self.tableView.setObjectName("tableView")
        self.add_book = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_book.setGeometry(QtCore.QRect(580, 170, 158, 61))
        self.add_book.setIconSize(QtCore.QSize(16, 20))
        self.add_book.setObjectName("add_book")
        self.delete_book = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_book.setGeometry(QtCore.QRect(580, 240, 158, 61))
        self.delete_book.setObjectName("delete_book")
        self.update_info = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update_info.setGeometry(QtCore.QRect(580, 310, 158, 61))
        self.update_info.setObjectName("update_info")
        self.search_method = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_method.setGeometry(QtCore.QRect(580, 100, 158, 61))
        self.search_method.setObjectName("search_method")
        self.db_connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.db_connect.setGeometry(QtCore.QRect(580, 30, 158, 61))
        self.db_connect.setObjectName("db_connect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Book Searcher", "Book Searcher"))
        self.add_book.setText(_translate("MainWindow", "Добавить книгу"))
        self.delete_book.setText(_translate("MainWindow", "Удалить книгу"))
        self.update_info.setText(_translate("MainWindow", "Редактировать"))
        self.search_method.setText(_translate("MainWindow", "Поиск"))
        self.db_connect.setText(_translate("MainWindow", "Подключить БД"))
